export const ROUTES = {
    HOME: '',
    OUR_SERVICES: 'our-services',
    OUR_PROCESS: 'our-process',
    AUSSIE_TOOLKIT: 'aussie-toolkit',
    UPSKILLING_RESOURCES: 'upskilling-resources',
    EVENTS_AND_NETWORKING: 'events-and-networking',
    RECRUITERS: 'recruiters',
    CONNECTION_BANK: 'connection-bank',
    JOB_SEARCH: 'job-search',
    BLOG: 'blog',
    BLOG_POST_PREFIX: 'blog-post',
    BLOG_POST: 'blog-post/:slug',
    CONTACT: 'contact',
    TERMS_AND_POLICIES: 'terms-and-policies',
    AUSTRALIAN_VISA_PATHWAYS: 'australian-visa-pathways',
    ABOUT_US: 'about-us',
}