import { FilterableCard } from '../models/filterable-card.model';
import { FilterConfig } from '../models/filter-config.model';

/** Subject filter values – use these in filterValues.subject (e.g. SUBJECT_OPTIONS.AI) */
const SUBJECT_OPTIONS = {
    AI: 'AI',
    Admin: 'Admin',
    Ads: 'Ads',
    Agile: 'Agile',
    Analytics: 'Analytics',
    Architecture: 'Architecture',
    Azure: 'Azure',
    Backend: 'Backend',
    Business: 'Business',
    CRM: 'CRM',
    Cloud: 'Cloud',
    Cloud_Computing: 'Cloud Computing',
    Compliance: 'Compliance',
    Computer_Science: 'Computer Science',
    Computing: 'Computing',
    Customer_Service: 'Customer Service',
    Cybersecurity: 'Cybersecurity',
    Data: 'Data',
    Data_Engineering: 'Data Engineering',
    Data_Science: 'Data Science',
    Databases: 'Databases',
    Design: 'Design',
    DevOps: 'DevOps',
    Development: 'Development',
    Digital: 'Digital',
    Digital_Marketing: 'Digital Marketing',
    Digital_Skills: 'Digital Skills',
    ERP: 'ERP',
    Education: 'Education',
    Employee_Training: 'Employee Training',
    Engineering: 'Engineering',
    Finance: 'Finance',
    HR: 'HR',
    Health: 'Health',
    Healthcare: 'Healthcare',
    IT: 'IT',
    IT_Ops: 'IT Ops',
    IT_Support: 'IT Support',
    Java: 'Java',
    Job_Readiness: 'Job Readiness',
    Leadership: 'Leadership',
    Management: 'Management',
    Marketing: 'Marketing',
    Math: 'Math',
    Networking: 'Networking',
    PM: 'PM',
    Photography: 'Photography',
    Power_BI: 'Power BI',
    Programming: 'Programming',
    Project_Management: 'Project Management',
    Python: 'Python',
    Recruitment: 'Recruitment',
    SQL: 'SQL',
    Sales: 'Sales',
    Science: 'Science',
    Scrum: 'Scrum',
    Security: 'Security',
    Short_Courses: 'Short Courses',
    Soft_Skills: 'Soft Skills',
    Software: 'Software',
    Statistics: 'Statistics',
    Sustainability: 'Sustainability',
    Tech: 'Tech',
    Tech_Skills: 'Tech Skills',
    Trades: 'Trades',
    Web_Dev: 'Web Dev',
} as const;

/** Price filter values – use these in filterValues.price (e.g. PRICE_OPTIONS.Free) */
const PRICE_OPTIONS = {
    Free: 'Free',
    Free_Exam_Paid: 'Free (exam paid)',
    Free_Optional_Paid_Certificate: 'Free (optional paid certificate)',
    Free_Paid_Cert: 'Free (paid cert)',
    Free_Paid: 'Free/Paid',
    Paid: 'Paid',
    Paid_Some_Free_Audit: 'Paid (some free audit)',
    Paid_Some_Free: 'Paid (some free)',
} as const;

/** Delivery filter values – use these in filterValues.delivery (e.g. DELIVERY_OPTIONS.Self_Paced) */
const DELIVERY_OPTIONS = {
    Self_Paced: 'Self Paced',
    Virtual: 'Virtual',
    Instructor_Led: 'Instructor Led',
    Hybrid: 'Hybrid',
} as const;

/** Default data for the upskilling resources page (when used without inputs) */
export const DEFAULT_UPSKILLING_CARDS: FilterableCard[] = [
    { name: 'Alison', description: 'Free online learning platform offering courses across business, IT and health. Learn more on the platform. Explore details.', metaTags: [PRICE_OPTIONS.Free_Optional_Paid_Certificate, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://alison.com', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.IT, SUBJECT_OPTIONS.Health], price: PRICE_OPTIONS.Free_Optional_Paid_Certificate, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Australian Institute of Management', description: 'Leadership and HR training. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://aim.com.au', filterValues: { subject: [SUBJECT_OPTIONS.Leadership, SUBJECT_OPTIONS.HR, SUBJECT_OPTIONS.Management], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
    { name: 'AWS Skill Builder', description: 'Cloud skills training by Amazon Web Services. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://skillbuilder.aws', filterValues: { subject: [SUBJECT_OPTIONS.Cloud_Computing, SUBJECT_OPTIONS.DevOps, SUBJECT_OPTIONS.Architecture], price: PRICE_OPTIONS.Free_Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Cisco Networking Academy', description: 'Networking and IT training programs. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://www.netacad.com', filterValues: { subject: [SUBJECT_OPTIONS.Networking, SUBJECT_OPTIONS.Cybersecurity, SUBJECT_OPTIONS.IT_Support], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
    { name: 'Codecademy', description: 'Interactive coding platform. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.codecademy.com', filterValues: { subject: [SUBJECT_OPTIONS.Programming, SUBJECT_OPTIONS.Web_Dev, SUBJECT_OPTIONS.Data_Science], price: PRICE_OPTIONS.Free_Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Coursera', description: 'Global learning platform with universities. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid_Some_Free_Audit, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.coursera.org', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Tech, SUBJECT_OPTIONS.Data, SUBJECT_OPTIONS.Health], price: PRICE_OPTIONS.Paid_Some_Free_Audit, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'DataCamp', description: 'Interactive data science and analytics learning platform. Learn more on the platform. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid_Some_Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.datacamp.com', filterValues: { subject: [SUBJECT_OPTIONS.Data_Science, SUBJECT_OPTIONS.Python, SUBJECT_OPTIONS.SQL, SUBJECT_OPTIONS.AI, SUBJECT_OPTIONS.Statistics], price: PRICE_OPTIONS.Paid_Some_Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'edX', description: 'University-backed online courses. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid_Cert, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.edx.org', filterValues: { subject: [SUBJECT_OPTIONS.Engineering, SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Computer_Science], price: PRICE_OPTIONS.Free_Paid_Cert, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Elevate Corporate Training', description: 'Corporate recruitment & sales training. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://www.elevatecorporatetraining.com.au', filterValues: { subject: [SUBJECT_OPTIONS.Recruitment, SUBJECT_OPTIONS.Leadership], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
    { name: 'FutureLearn', description: 'Short courses and programs globally. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.futurelearn.com', filterValues: { subject: [SUBJECT_OPTIONS.Healthcare, SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Education, SUBJECT_OPTIONS.Tech], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Generation Australia', description: 'Free bootcamp-style training. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Virtual], link: 'https://www.generation.org/australia', filterValues: { subject: [SUBJECT_OPTIONS.Tech_Skills, SUBJECT_OPTIONS.Job_Readiness], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Google Cloud Skills Boost', description: 'Hands-on cloud labs. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.cloudskillsboost.google', filterValues: { subject: [SUBJECT_OPTIONS.Cloud_Computing, SUBJECT_OPTIONS.Data, SUBJECT_OPTIONS.AI], price: PRICE_OPTIONS.Free_Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Hays Learning', description: 'Free professional development platform. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://learning.hays.com', filterValues: { subject: [SUBJECT_OPTIONS.Soft_Skills, SUBJECT_OPTIONS.Digital_Skills], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'HubSpot Academy', description: 'Free business and marketing certifications. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://academy.hubspot.com', filterValues: { subject: [SUBJECT_OPTIONS.Marketing, SUBJECT_OPTIONS.Sales, SUBJECT_OPTIONS.CRM, SUBJECT_OPTIONS.Customer_Service], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'IBM SkillsBuild', description: 'Free skills development programs for technology careers. Learn more on the platform. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://skillsbuild.org', filterValues: { subject: [SUBJECT_OPTIONS.AI, SUBJECT_OPTIONS.Data, SUBJECT_OPTIONS.Cloud, SUBJECT_OPTIONS.Cybersecurity], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Khan Academy', description: 'Free education platform. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.khanacademy.org', filterValues: { subject: [SUBJECT_OPTIONS.Math, SUBJECT_OPTIONS.Science, SUBJECT_OPTIONS.Computing, SUBJECT_OPTIONS.Finance], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'LinkedIn Learning', description: 'Professional skills development. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.linkedin.com/learning', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Tech, SUBJECT_OPTIONS.Leadership], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Meta Blueprint', description: 'Training for Meta platforms. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.facebook.com/business/learn', filterValues: { subject: [SUBJECT_OPTIONS.Digital_Marketing, SUBJECT_OPTIONS.Ads, SUBJECT_OPTIONS.Analytics], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Microsoft Learn', description: 'Official Microsoft training for cloud and tech roles. Learn more on the platform. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Exam_Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://learn.microsoft.com', filterValues: { subject: [SUBJECT_OPTIONS.Azure, SUBJECT_OPTIONS.AI, SUBJECT_OPTIONS.Data, SUBJECT_OPTIONS.Power_BI, SUBJECT_OPTIONS.Security], price: PRICE_OPTIONS.Free_Exam_Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'MongoDB University', description: 'Free NoSQL and backend development training. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://university.mongodb.com', filterValues: { subject: [SUBJECT_OPTIONS.Databases, SUBJECT_OPTIONS.Backend, SUBJECT_OPTIONS.Data_Engineering], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Open Universities Australia', description: 'Online microcredentials from Australian universities. Learn more on the platform. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.open.edu.au', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.IT, SUBJECT_OPTIONS.Health], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'OpenLearning', description: 'Microcredential marketplace. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.openlearning.com', filterValues: { subject: [SUBJECT_OPTIONS.Short_Courses, SUBJECT_OPTIONS.Digital_Skills], price: PRICE_OPTIONS.Free_Paid, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Oracle University', description: 'Training and certifications on Oracle technologies. Learn more on the platform. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://education.oracle.com', filterValues: { subject: [SUBJECT_OPTIONS.Databases, SUBJECT_OPTIONS.Cloud, SUBJECT_OPTIONS.Java, SUBJECT_OPTIONS.ERP], price: PRICE_OPTIONS.Free_Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Pluralsight', description: 'Tech-focused skill development platform. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.pluralsight.com', filterValues: { subject: [SUBJECT_OPTIONS.Software, SUBJECT_OPTIONS.Cloud, SUBJECT_OPTIONS.IT_Ops, SUBJECT_OPTIONS.Cybersecurity], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'PMI', description: 'Project management certifications and training. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://www.pmi.org', filterValues: { subject: [SUBJECT_OPTIONS.Project_Management, SUBJECT_OPTIONS.Agile], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
    { name: 'RMIT Online', description: 'University-backed online courses. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://online.rmit.edu.au', filterValues: { subject: [SUBJECT_OPTIONS.HR, SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Analytics], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'RMIT University Short Courses', description: 'Short courses and microcredentials. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Hybrid], link: 'https://www.rmit.edu.au', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Tech, SUBJECT_OPTIONS.Design], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Hybrid] } },
    { name: 'Salesforce Trailhead', description: 'Hands-on learning for Salesforce ecosystem. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://trailhead.salesforce.com', filterValues: { subject: [SUBJECT_OPTIONS.CRM, SUBJECT_OPTIONS.Admin, SUBJECT_OPTIONS.Development, SUBJECT_OPTIONS.Analytics], price: PRICE_OPTIONS.Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Scrum.org', description: 'Agile and Scrum certifications. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.scrum.org', filterValues: { subject: [SUBJECT_OPTIONS.Agile, SUBJECT_OPTIONS.Scrum], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'SEEK Learning', description: 'Australian training marketplace. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Hybrid], link: 'https://www.seeklearning.com.au', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.IT, SUBJECT_OPTIONS.HR, SUBJECT_OPTIONS.PM], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Hybrid] } },
    { name: 'Skillshare', description: 'Creative and business learning. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.skillshare.com', filterValues: { subject: [SUBJECT_OPTIONS.Design, SUBJECT_OPTIONS.Photography, SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Marketing], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'TAFE Digital', description: 'Online vocational learning. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.tafensw.edu.au/digital', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.IT, SUBJECT_OPTIONS.HR, SUBJECT_OPTIONS.Trades], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'TAFE NSW', description: 'Vocational and HR related training. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://www.tafensw.edu.au', filterValues: { subject: [SUBJECT_OPTIONS.HR, SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Trades], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
    { name: 'TalentLMS', description: 'Cloud learning management system. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Free_Paid, DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual], link: 'https://www.talentlms.com', filterValues: { subject: [SUBJECT_OPTIONS.Employee_Training, SUBJECT_OPTIONS.Compliance], price: PRICE_OPTIONS.Free_Paid, delivery: [DELIVERY_OPTIONS.Hybrid, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Udacity', description: 'Nanodegree programs for tech roles. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Virtual], link: 'https://www.udacity.com', filterValues: { subject: [SUBJECT_OPTIONS.AI, SUBJECT_OPTIONS.Data, SUBJECT_OPTIONS.Cloud, SUBJECT_OPTIONS.Programming], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Virtual] } },
    { name: 'Udemy', description: 'On-demand skills courses. Learn more on the platform. Explore details. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid_Some_Free, DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual], link: 'https://www.udemy.com', filterValues: { subject: [SUBJECT_OPTIONS.IT, SUBJECT_OPTIONS.Marketing, SUBJECT_OPTIONS.Design, SUBJECT_OPTIONS.Business], price: PRICE_OPTIONS.Paid_Some_Free, delivery: [DELIVERY_OPTIONS.Self_Paced, DELIVERY_OPTIONS.Virtual] } },
    { name: 'University of Melbourne Short Courses', description: 'Professional development programs. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://shortcourses.unimelb.edu.au', filterValues: { subject: [SUBJECT_OPTIONS.Leadership, SUBJECT_OPTIONS.Digital, SUBJECT_OPTIONS.Sustainability], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
    { name: 'Victoria University Microcredentials', description: 'University short skill-based courses. Learn more on the platform. Explore details. Explore details. Explore details.', metaTags: [PRICE_OPTIONS.Paid, DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid], link: 'https://www.vu.edu.au', filterValues: { subject: [SUBJECT_OPTIONS.Business, SUBJECT_OPTIONS.Digital, SUBJECT_OPTIONS.Education], price: PRICE_OPTIONS.Paid, delivery: [DELIVERY_OPTIONS.Instructor_Led, DELIVERY_OPTIONS.Hybrid] } },
];

/** Default filters for upskilling (3 filters: subject, price, delivery) */
export const DEFAULT_UPSKILLING_FILTERS: FilterConfig[] = [
    { id: 'subject', label: 'Select Subjects...', options: Object.values(SUBJECT_OPTIONS), multiSelect: true },
    { id: 'price', label: 'Free or Paid...', options: Object.values(PRICE_OPTIONS), multiSelect: false },
    { id: 'delivery', label: 'Delivery...', options: Object.values(DELIVERY_OPTIONS), multiSelect: true },
];
